config/routes.rb
Rails.application.routes.draw do
  root to: 'users#show'
  devise_for :users

  resources :balance_rings
  resources :balances
  resources :categories
  resources :expenses,        only: [:show, :index, :new, :create]
  resources :fixed_expenses,  only: [:show, :index, :edit]
  resources :homes,           only: [:show]
  resources :incomes,         only: [:show, :index, :edit]
  resources :user,            only: [:show, :index, :edit]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :users do
  #   resources :fixed_expenses
  # end

  # resources :users do
  #   resources :incomes
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/balance.rb
class Balance < ApplicationRecord
end

app/models/balance_ring.rb
class BalanceRing < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :expenses, dependent: :destroy
  belongs_to :user

  validates :name
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/models/fixed_expense.rb
class FixedExpense < ApplicationRecord
end

app/models/income.rb
class Income < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name,   presence: true
  validates :first_name,  presence: true
  validates :email,       presence: true

  has_many :expenses, dependent: :destroy
  has_many :categories, dependent: :destroy
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end


  def edit
    @user = current_user
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def edit
    @user = current_user
  end

  def show
    @user = current_user
  end

  private
  
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balance_rings_helper.rb
module BalanceRingsHelper
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/fixed_expenses_helper.rb
module FixedExpensesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>hoWseed</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/051eb814e7.js" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="nav_header">
      <%= link_to image_tag("logo.png", size:"100x100"), root_path %>
    </div>
    <header class="">
      <div class="hamburger position-absolute top-10 end-10">
        <span></span>
        <span></span>
        <span></span>
      </div>

      <nav class="globalMenuSp navbar navbar-expand-lg navbar-dark justify-content-between">
        <ul>
        
        <% if user_signed_in? %>
          <li id="for-logout-button"><%= link_to "Contact", root_path, class: "text-secondary" %></li>
          <span class="">
            <li>
              <!-- Example single danger button -->
              <div class="btn-group">
                  <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                      aria-expanded="false">Settings</button>
                  <div class="dropdown-menu">
                      <div class="dropdown-item"><%= link_to "User Information", edit_user_registration_path(current_user.id), class: "text-secondary" %></div>
                      <div class="dropdown-item"><%= link_to "Fixed Expenses", fixed_expenses_path(current_user.id), class: "text-secondary" %></div>
                      <div class="dropdown-item"><%= link_to "Incomes", incomes_path(current_user.id), class: "text-secondary" %></div>
                      <div class="dropdown-divider"></div>
                      <div class="dropdown-item">Separated link</div>
                  </div>
              </div><!-- /btn-group -->
            </li><br>
          </span>
          <li><%= button_to "ログアウト", destroy_user_session_path, method: :delete, class:"btn btn-outline-danger" %></li>
        <% else %>
          <li id="for-logout-button"><a href="#">About</a></li>
          <li id="for-logout-button"><a href="#">Features</a></li>
          <li id="for-logout-button"><a href="#">Contact</a></li>
          <li id="for-logout-button"><%= link_to "新規登録", new_user_registration_path %></li><br>
          <li><%= button_to "ログイン", new_user_session_path, class:"btn btn-outline-primary" %></li>
        <% end %>
        </ul>
      </nav>
    </header>
    <script type="text/javascript">
      $(function() {
        $('.hamburger').click(function() {
          $(this).toggleClass('active');
  
          if ($(this).hasClass('active')) {
              $('.globalMenuSp').addClass('active');
          } else {
              $('.globalMenuSp').removeClass('active');
          }
        });
      });
    </script>
  </body>
  <main>
    <div>
      <p class="text-success"><%= notice %></p>
      <p class="text-danger"><%= alert %></p>
      <div id="content"><%= yield %></div>
    </div>
  </main>
  <footer class="footer">
    <div class="container text-center">
      <div class="text-center">
        <%= image_tag("logo.png", size: "100x100") %>
        <p></p>
        <div class="footer_copyright">
          Copyright &copy; 1992 - 2022 hoWseed Inc. All Rights Reserved.
        </div>
      </div>
    </div>
  </footer>
  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>

</html>